### PR TITLE
DSO-646 Upgrade Libre Office to existing repository 7.3.5

### PR DESCRIPTION
**Pull request by martinbozinovski**

### CODE REVIEW

**Review by sparksam — APPROVED** [review]
Looks good to me.

**Review by dzdimov — APPROVED** [review]

**Comment by martinbozinovski** [comment]
@david-oc-miller Please review this when you can, it is failing the installer and blocking the release of 2022.01-RC2 for Core and Foia Test env.

**Comment by david-oc-miller** [comment]
@martinbozinovski this can't possibly block anything since you could just set the `libreoffice_version` to whatever you need in the facts file.  7.3.5 is only the default value, you can set the fact to anything you need in any particular install.

**Review by david-oc-miller — APPROVED** [review]

**Comment by martinbozinovski** [comment]
You are right..I probably wanted unified for all installs, and wrote the first thing that pop on my mind :) Btw, thanks!

**Pull request merged**
